trigger:
  branches:
    include:
    - refs/heads/main

variables:
  buildFolderName: output
  buildArtifactName: MOFFiles

pool: 
  name: 'pool-m365dsc2'
  #vmImage: windows-latest

stages:
  - stage: Compile
    jobs:
      - job: CompileConfiguration
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: azdo-m365dsc-service-endpoint
            ScriptType: 'FilePath'
            scriptPath: ./DSC/build.ps1
            azurePowerShellVersion: latestVersion
            pwsh: false
            errorActionPreference: 'stop'
            failOnStandardError: true

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Artifacts to Pipeline'
          inputs:
            targetPath: '$(buildFolderName)/'
            artifact: $(buildArtifactName)
            publishLocation: 'pipeline'
            parallel: true
